spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Documentación API (http://localhost:8081/swagger-ui.html )
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
